### PR TITLE
Pull request to eventually merge with phys767 file

### PR DESCRIPTION
**Pull request by drewjrosen**
Final project is in plottinggaia.py with associated travis test file.

### CODE REVIEW

**Comment by kelle** [comment]
@zhiyanwang Please review this PR.

**Comment by zhiyanwang** [comment]
@drewjrosen @kelle 
Your main code " plottinggaia.py" is clean and easy to read. Just a couple suggestions for the entire project.

For the Travis test, since we need to input "tgas-source.fits" to run the code, and it's too large to be uploaded, the Travis test will fail eventually. However, creating a "requirements.txt" can help Travis install "matplotlib" and "astropy", which will be required to run your code anyway.

I couldn't find the 3D position-velocity map you mentioned in your README. Uploading this plot will be very helpful to understand your result.

**Comment by drewjrosen** [comment]
Added the necessary requirements file. Added two frames from the 3D plot.

**Comment by kelle** [comment]
@zhiyanwang Your comments are useful but please start a review and "approve" the PR.

**Review by zhiyanwang — APPROVED** [review]

**Review by zhiyanwang — COMMENTED** [review]
The newly uploaded plot is a good demonstration of the velocity of stars from in the Gaia project. Although it's hard to see the exact 3-dimensional positions in this plot, the arrow vectors show the magnitude of velocities well.

Comparing to what I concluded from my plot, it seems that the magnitude of transverse velocity does not depend on the position of these stars, at least not in an apparent way.

@kelle Please let me know if there is anything else I should contribute. Thank you.

**Pull request merged**
